<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo: http://leoeditor.com/leo_toc.html -->
<leo_file xmlns:leo="http://leoeditor.com/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2"/>
<globals/>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="qkmoore.20190215232943.2"><vh>NewHeadline</vh></v>
</vnodes>
<tnodes>
<t tx="qkmoore.20190215232943.2"></t>
</tnodes>
</leo_file>
